{
  imports = [
    ./alpha.nix
    ./bbye.nix
    ./ccc.nix
    ./fidget.nix
    ./gitsigns.nix
    ./highlight-yank.nix
    ./illuminate.nix
    ./indent-blankline.nix
    ./lastplace.nix
    ./noice.nix
    ./notify.nix
    ./rainbow-delimiters.nix
    ./theme
    ./undotree.nix
    ./which-key.nix
  ];
}
